In [1]:
#pip install numpy
# To install numpy

In [2]:
import numpy as np

In [3]:
myList=[1,2,3,4,5]

In [4]:
print(myList)

[1, 2, 3, 4, 5]


In [5]:
type(myList)

list

In [6]:
#dir(np) 

In [7]:
#help(np)

In [8]:
arr=np.array(myList)

In [9]:
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
#shape of the array
arr.shape

(5,)

In [11]:
#size of the array
arr.size

5

In [12]:
my_list1=[1,2,3,4]
my_list2=[2,4,5,6]
my_list3=[9,8,7,4]
arr = np.array([my_list1,my_list2,my_list3])

In [13]:
# Numpy array indexing
# Get the first element from the following elements
my_list=[1,2,3,4,5]
arr = np.array(my_list)

In [14]:
arr

array([1, 2, 3, 4, 5])

In [15]:
print(arr[0])

1


In [16]:
# print the zecond element 
print(arr[1])

2


In [17]:
# get the 3rd and 4th element and add them
print("The third element is",arr[2],"and fourth element is",arr[3])

The third element is 3 and fourth element is 4


In [18]:
my_list1=[1,2,3,4]
my_list2=[2,4,5,6]
my_list3=[9,8,7,4]
arr = np.array([my_list1,my_list2,my_list3])

In [19]:
arr

array([[1, 2, 3, 4],
       [2, 4, 5, 6],
       [9, 8, 7, 4]])

In [20]:
arr[0,2]  # here 0 is the first row and 2 is the column

3

In [21]:
# access the second row and 5th column
arr[1,3]

6

In [22]:
va1Arr = np.array([[1,2,3],[2,3,4]])
# print the variable
# print the shape
# print size
# index first row first element
# index second row 3rd element


In [23]:
va1Arr

array([[1, 2, 3],
       [2, 3, 4]])

In [24]:
print("Printing the variable value",va1Arr,"\n")
print("Printing the size",va1Arr.size,"\n")
print("Printing the shape",va1Arr.shape,"\n")
print(" Indexing 1st row 1st element",va1Arr[0,0],"\n")
print("Indexing 2nd row 3rd element",va1Arr[1,2],"\n")


Printing the variable value [[1 2 3]
 [2 3 4]] 

Printing the size 6 

Printing the shape (2, 3) 

 Indexing 1st row 1st element 1 

Indexing 2nd row 3rd element 4 



In [25]:
# negative indexing 
# accesing from the back
mylist=[1,2,3,4,5,6,7]
arr = np.array(mylist)
print(arr)

[1 2 3 4 5 6 7]


In [26]:
mylist[-1]

7

In [27]:
valArr = np.array([[1,2,3],[2,3,4]])
print(valArr)

[[1 2 3]
 [2 3 4]]


In [28]:
# to print 4
valArr[1,-1]

4

In [29]:
valArr[1,-3]

2

In [30]:
# Slicing 
# it means taking acset of elements
mylist=[1,2,3,4,5,6,7,8]
arr = np.array(mylist)
print(arr)

[1 2 3 4 5 6 7 8]


In [31]:
#arr[start:end]
# to print from 1to5
arr[0:5]

array([1, 2, 3, 4, 5])

In [32]:
# to print from 4 to end
arr[3:]

array([4, 5, 6, 7, 8])

In [33]:
# to print 1st 5 elements
arr[:5]

array([1, 2, 3, 4, 5])

In [34]:
# Negative slicing
arr[:-1]

array([1, 2, 3, 4, 5, 6, 7])

In [35]:
arr[-3:-1]

array([6, 7])

In [36]:
# Step function or intervals
arr[::2]

array([1, 3, 5, 7])

In [37]:
# slicing 2-D arrays
#arr[:,:] 1st is row and second is column
my_list1=[1,2,3,4]
my_list2=[2,4,5,6]
my_list3=[9,8,7,4]
arr = np.array([my_list1,my_list2,my_list3])
print(arr)

[[1 2 3 4]
 [2 4 5 6]
 [9 8 7 4]]


In [38]:
arr[0:1,1:3]

array([[2, 3]])

In [39]:
# Arange function
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [40]:
# linspace
np.linspace(0,100)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [41]:
arr = np.array([1,2,3,4,5],dtype='S')
print(arr)

[b'1' b'2' b'3' b'4' b'5']


In [42]:
arr = np.array([1,2,3,4,5],dtype=np.int64)
print(arr.dtype)

int64


In [43]:
arr = np.array([1,2,3,4,5],dtype=np.float32)
print(arr.dtype)

float32


In [44]:
# array math operations
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)


In [45]:
print(x)
print("--")
print(y)

[[1. 2.]
 [3. 4.]]
--
[[5. 6.]
 [7. 8.]]


In [46]:
x+y

array([[ 6.,  8.],
       [10., 12.]])

In [47]:
x-y

array([[-4., -4.],
       [-4., -4.]])

In [48]:
np.subtract(x,y)

array([[-4., -4.],
       [-4., -4.]])

In [49]:
np.add(x,y)

array([[ 6.,  8.],
       [10., 12.]])

In [50]:
np.multiply(x,y)

array([[ 5., 12.],
       [21., 32.]])

In [51]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [52]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [53]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [54]:
x.shape

(2, 2)

In [55]:
y.shape

(2, 2)

In [56]:
# Make a copy, change the original array, and display both arrays:

arr = np.array([1, 2, 3, 4, 5])
x = arr




In [57]:
print(arr)

[1 2 3 4 5]


In [58]:
print(x)

[1 2 3 4 5]


In [59]:
arr[0]=100

In [60]:
print(arr)

[100   2   3   4   5]


In [61]:
print(x)

[100   2   3   4   5]


In [62]:
x[1]=200

In [63]:
print(x)

[100 200   3   4   5]


In [64]:
print(arr)

[100 200   3   4   5]


In [65]:
# Make a copy, change the original array, and display both arrays:

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()


In [66]:
print(arr)

[1 2 3 4 5]


In [67]:
print(x)

[1 2 3 4 5]


In [68]:
arr[0]=100

In [69]:
print(arr)

[100   2   3   4   5]


In [70]:
print(x)

[1 2 3 4 5]


In [71]:
x[1]=100

In [72]:
print(x)

[  1 100   3   4   5]


In [73]:
print(arr)

[100   2   3   4   5]


In [74]:
# NumPy Array Reshaping
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])


In [77]:
arr = np.arange(1,13)

In [78]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [81]:
arr_new = arr.reshape(4,3) #1D---> 2D

In [83]:
arr_new

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [84]:
# Flattening the arrays
# 2d to 1D
arr_new

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [85]:
arr_new.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [95]:
# Iterating Arrays
arr = np.arange(1,7).reshape(3,2)

In [96]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [97]:
for x in arr:
    print(x)

[1 2]
[3 4]
[5 6]


In [98]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

In [99]:
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [100]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])


In [101]:
np.concatenate((arr1,arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])